#=============================================================
# API definitiion file usually openapi 3.x yaml format
# API definitiion file usually openapi 3.x yaml format
#=============================================================
definitions: 
  - name: self
    default: true
    path: ~

#=============================================================
# Paths to look for .spec.yml files
# @todo need to cache all file list
# @todo cache rebuild needed --no-cache
#
#=============================================================
# filePath: . # means default config, which is current dir
# filePath: ./some-folder # relative path
# filePath: /User/mahmudul.hasan/testbase # absolute path
#=============================================================
file_path: .

#=============================================================
# drivers
# Driver is a runner plugin that runs `.spec.yml` and `.flow.yml`
# files with `chk run ...` gets called in console
#=============================================================
drivers:
  - name: RestSpecRunner
    default: true
    # alternative to context.driver_payload in .spec.yml files
    payload: ~